jvmbrotliversion: 0.2.0
repourl: https://github.com/nixxcode/jvm-brotli
description: Jvm-Brotli - Lightweight, cross-platform Java library for the Brotli compression format.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
